
/**
 * App Code Generator
 * Generates production-ready code from app designs
 */

import { AppStructure } from './app-inspector';

export interface GeneratorOptions {
  includeComments?: boolean;
  includeTypeScript?: boolean;
  includeApiIntegration?: boolean;
  includeStateManagement?: boolean;
}

export interface ColorCustomization {
  primary?: string;
  secondary?: string;
  accent?: string;
  background?: string;
  text?: string;
  border?: string;
}

export interface LayoutCustomization {
  paneLayout: '1-pane' | '2-pane' | '3-pane';
  headerStyle: 'gradient' | 'flat' | 'minimal';
  navigationWidth?: string;
  listWidth?: string;
  hasStatusBar: boolean;
  hasHeader: boolean;
  hasToolbar: boolean;
  hasGestureArea: boolean;
}

export class AppCodeGenerator {
  /**
   * Generate complete app code
   */
  static generateAppCode(
    appName: string,
    description: string,
    layout: LayoutCustomization,
    colors: ColorCustomization,
    options: GeneratorOptions = {}
  ): string {
    const componentName = this.sanitizeComponentName(appName);
    const imports = this.generateImports(layout, options);
    const stateManagement = options.includeStateManagement
      ? this.generateStateManagement()
      : '';
    const apiIntegration = options.includeApiIntegration
      ? this.generateApiIntegration(componentName)
      : '';

    return `'use client';

${imports}

${options.includeComments ? `/**
 * ${appName}
 * ${description}
 * 
 * Generated by App Designer
 * Layout: ${layout.paneLayout}
 * Pattern: ${layout.headerStyle}
 */` : ''}

export default function ${componentName}() {
  ${stateManagement}
  ${apiIntegration}

  return (
    <div className="h-screen flex flex-col bg-white">
      ${layout.hasStatusBar ? this.generateStatusBar(appName, colors) : ''}
      ${layout.hasHeader ? this.generateHeader(appName, description, layout.headerStyle, colors) : ''}
      
      <div className="flex-1 flex overflow-hidden">
        ${this.generateContentArea(layout, colors)}
      </div>

      ${layout.hasToolbar ? this.generateToolbar(colors) : ''}
      ${layout.hasGestureArea ? this.generateGestureArea() : ''}
    </div>
  );
}`;
  }

  /**
   * Generate component imports
   */
  private static generateImports(layout: LayoutCustomization, options: GeneratorOptions): string {
    const imports = ['React', 'useState'];
    
    if (options.includeStateManagement) {
      imports.push('useEffect');
    }

    const iconImports = [
      'Search',
      'Filter',
      'Plus',
      'MoreVertical',
      'ChevronRight',
      'ChevronLeft',
      'Home',
      'Settings'
    ];

    return `import React, { ${imports.join(', ')} } from 'react';
import { ${iconImports.join(', ')} } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';
${options.includeStateManagement ? "import { toast } from 'sonner';" : ''}`;
  }

  /**
   * Generate state management code
   */
  private static generateStateManagement(): string {
    return `  // State management
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedItem, setSelectedItem] = useState<string | null>(null);
  const [items, setItems] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [filters, setFilters] = useState({
    category: 'all',
    status: 'all',
  });`;
  }

  /**
   * Generate API integration code
   */
  private static generateApiIntegration(componentName: string): string {
    const apiEndpoint = componentName.toLowerCase().replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
    
    return `
  // API integration
  useEffect(() => {
    loadData();
  }, [filters]);

  const loadData = async () => {
    setIsLoading(true);
    try {
      const response = await fetch('/api/${apiEndpoint}');
      if (!response.ok) throw new Error('Failed to load data');
      const data = await response.json();
      setItems(data);
    } catch (error) {
      console.error('Failed to load data:', error);
      toast.error('Failed to load data');
    } finally {
      setIsLoading(false);
    }
  };

  const handleCreate = async () => {
    // Implement create functionality
    toast.success('Item created successfully');
    loadData();
  };

  const handleUpdate = async (id: string) => {
    // Implement update functionality
    toast.success('Item updated successfully');
    loadData();
  };

  const handleDelete = async (id: string) => {
    // Implement delete functionality
    toast.success('Item deleted successfully');
    loadData();
  };`;
  }

  /**
   * Generate status bar
   */
  private static generateStatusBar(appName: string, colors: ColorCustomization): string {
    const bgColor = colors.primary || '#1F2937';
    return `
      {/* Status Bar */}
      <div 
        className="px-4 py-2 text-xs flex justify-between items-center text-white"
        style={{ backgroundColor: '${bgColor}' }}
      >
        <span className="font-semibold">{appName}</span>
        <span>{new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
      </div>`;
  }

  /**
   * Generate header
   */
  private static generateHeader(
    appName: string,
    description: string,
    style: 'gradient' | 'flat' | 'minimal',
    colors: ColorCustomization
  ): string {
    const bgStyles = {
      gradient: 'bg-gradient-to-b from-gray-100 to-gray-200',
      flat: 'bg-gray-50',
      minimal: 'bg-white',
    };

    return `
      {/* Header */}
      <div className="${bgStyles[style]} px-6 py-4 border-b border-gray-200">
        <h1 className="text-4xl font-light text-gray-600 tracking-wide">
          ${appName.toUpperCase()}
        </h1>
        <p className="text-sm text-gray-500 mt-0.5">${description}</p>
      </div>`;
  }

  /**
   * Generate content area based on layout
   */
  private static generateContentArea(layout: LayoutCustomization, colors: ColorCustomization): string {
    if (layout.paneLayout === '3-pane') {
      return this.generate3PaneLayout(layout, colors);
    } else if (layout.paneLayout === '2-pane') {
      return this.generate2PaneLayout(layout, colors);
    } else {
      return this.generate1PaneLayout(layout, colors);
    }
  }

  /**
   * Generate 3-pane layout
   */
  private static generate3PaneLayout(layout: LayoutCustomization, colors: ColorCustomization): string {
    return `
        {/* Navigation Pane */}
        <div className="w-60 bg-gradient-to-b from-gray-200 to-gray-300 border-r border-gray-400 p-4">
          <div className="space-y-2">
            {['All Items', 'Recent', 'Favorites', 'Archive'].map((category, idx) => (
              <button
                key={idx}
                className="w-full text-left px-4 py-2 rounded-lg hover:bg-white/50 transition-all text-gray-700 font-medium"
                onClick={() => setFilters({ ...filters, category: category.toLowerCase() })}
              >
                {category}
              </button>
            ))}
          </div>
        </div>

        {/* List Pane */}
        <div className="w-96 bg-white border-r border-gray-200 flex flex-col">
          <div className="p-4 border-b border-gray-200">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
              <Input
                className="pl-10"
                placeholder="Search..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
          </div>
          
          <ScrollArea className="flex-1">
            <div className="p-4 space-y-3">
              {isLoading ? (
                <div className="text-center py-8 text-gray-400">Loading...</div>
              ) : items.length === 0 ? (
                <div className="text-center py-8 text-gray-400">No items found</div>
              ) : (
                items
                  .filter(item => 
                    !searchQuery || 
                    item.title?.toLowerCase().includes(searchQuery.toLowerCase())
                  )
                  .map((item, idx) => (
                    <Card
                      key={idx}
                      className={\`p-4 cursor-pointer transition-all hover:shadow-md \${
                        selectedItem === item.id ? 'ring-2 ring-blue-500' : ''
                      }\`}
                      onClick={() => setSelectedItem(item.id)}
                    >
                      <h3 className="font-semibold text-gray-900">{item.title || \`Item \${idx + 1}\`}</h3>
                      <p className="text-sm text-gray-500 mt-1">{item.description || 'No description'}</p>
                      {item.category && (
                        <Badge className="mt-2" variant="secondary">{item.category}</Badge>
                      )}
                    </Card>
                  ))
              )}
            </div>
          </ScrollArea>

          <div className="p-4 border-t border-gray-200">
            <Button className="w-full" onClick={handleCreate}>
              <Plus size={16} className="mr-2" />
              New Item
            </Button>
          </div>
        </div>

        {/* Detail Pane */}
        <div className="flex-1 bg-gray-50 p-6">
          {selectedItem ? (
            <div className="bg-white rounded-lg shadow-sm p-6 h-full">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-semibold text-gray-900">Item Details</h2>
                <div className="flex gap-2">
                  <Button variant="outline" size="sm">
                    <Settings size={16} />
                  </Button>
                  <Button variant="outline" size="sm">
                    <MoreVertical size={16} />
                  </Button>
                </div>
              </div>
              
              <div className="space-y-6">
                <div>
                  <label className="text-sm font-medium text-gray-700">Title</label>
                  <Input className="mt-1" placeholder="Enter title" />
                </div>
                
                <div>
                  <label className="text-sm font-medium text-gray-700">Description</label>
                  <textarea
                    className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-lg resize-none"
                    rows={4}
                    placeholder="Enter description"
                  />
                </div>

                <div className="flex gap-2">
                  <Button onClick={() => handleUpdate(selectedItem)}>
                    Save Changes
                  </Button>
                  <Button variant="outline">
                    Cancel
                  </Button>
                </div>
              </div>
            </div>
          ) : (
            <div className="flex items-center justify-center h-full text-gray-400">
              <div className="text-center">
                <ChevronLeft size={48} className="mx-auto mb-4 opacity-50" />
                <p className="text-lg">Select an item to view details</p>
              </div>
            </div>
          )}
        </div>`;
  }

  /**
   * Generate 2-pane layout
   */
  private static generate2PaneLayout(layout: LayoutCustomization, colors: ColorCustomization): string {
    return `
        {/* List Pane */}
        <div className="w-96 bg-white border-r border-gray-200 flex flex-col">
          <div className="p-4 border-b border-gray-200">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
              <Input
                className="pl-10"
                placeholder="Search..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
          </div>
          
          <ScrollArea className="flex-1">
            <div className="p-4 space-y-3">
              {items.map((item, idx) => (
                <Card
                  key={idx}
                  className={\`p-4 cursor-pointer transition-all hover:shadow-md \${
                    selectedItem === item.id ? 'ring-2 ring-blue-500' : ''
                  }\`}
                  onClick={() => setSelectedItem(item.id)}
                >
                  <h3 className="font-semibold text-gray-900">{item.title || \`Item \${idx + 1}\`}</h3>
                  <p className="text-sm text-gray-500 mt-1">{item.description || 'No description'}</p>
                </Card>
              ))}
            </div>
          </ScrollArea>

          <div className="p-4 border-t border-gray-200">
            <Button className="w-full" onClick={handleCreate}>
              <Plus size={16} className="mr-2" />
              New Item
            </Button>
          </div>
        </div>

        {/* Detail Pane */}
        <div className="flex-1 bg-gray-50 p-6">
          {selectedItem ? (
            <div className="bg-white rounded-lg shadow-sm p-6">
              <h2 className="text-2xl font-semibold text-gray-900 mb-6">Item Details</h2>
              <div className="space-y-4">
                <Input placeholder="Title" />
                <textarea
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg resize-none"
                  rows={6}
                  placeholder="Description"
                />
                <Button onClick={() => handleUpdate(selectedItem)}>Save Changes</Button>
              </div>
            </div>
          ) : (
            <div className="flex items-center justify-center h-full text-gray-400">
              <p className="text-lg">Select an item to view details</p>
            </div>
          )}
        </div>`;
  }

  /**
   * Generate 1-pane layout
   */
  private static generate1PaneLayout(layout: LayoutCustomization, colors: ColorCustomization): string {
    return `
        {/* Single Pane */}
        <div className="flex-1 bg-white p-4">
          <div className="mb-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
              <Input
                className="pl-10"
                placeholder="Search..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
          </div>

          <ScrollArea className="h-full">
            <div className="space-y-3">
              {items.map((item, idx) => (
                <Card
                  key={idx}
                  className="p-4 cursor-pointer transition-all hover:shadow-md"
                  onClick={() => setSelectedItem(item.id)}
                >
                  <h3 className="font-semibold text-gray-900">{item.title || \`Item \${idx + 1}\`}</h3>
                  <p className="text-sm text-gray-500 mt-1">{item.description || 'No description'}</p>
                </Card>
              ))}
            </div>
          </ScrollArea>

          <div className="fixed bottom-20 right-6">
            <Button size="lg" className="rounded-full shadow-lg" onClick={handleCreate}>
              <Plus size={24} />
            </Button>
          </div>
        </div>`;
  }

  /**
   * Generate toolbar
   */
  private static generateToolbar(colors: ColorCustomization): string {
    return `
      {/* Toolbar */}
      <div className="bg-gradient-to-r from-gray-700 to-gray-600 px-6 py-3 flex justify-center gap-8 border-t border-gray-800">
        <button className="flex flex-col items-center gap-1 text-gray-300 hover:text-white transition-colors">
          <Home size={20} />
          <span className="text-xs">Home</span>
        </button>
        <button className="flex flex-col items-center gap-1 text-gray-300 hover:text-white transition-colors">
          <Search size={20} />
          <span className="text-xs">Search</span>
        </button>
        <button className="flex flex-col items-center gap-1 text-gray-300 hover:text-white transition-colors">
          <Plus size={20} />
          <span className="text-xs">New</span>
        </button>
        <button className="flex flex-col items-center gap-1 text-gray-300 hover:text-white transition-colors">
          <Settings size={20} />
          <span className="text-xs">Settings</span>
        </button>
      </div>`;
  }

  /**
   * Generate gesture area
   */
  private static generateGestureArea(): string {
    return `
      {/* Gesture Area */}
      <div className="bg-black py-3 flex justify-center">
        <div className="w-28 h-1 bg-gray-700 rounded-full"></div>
      </div>`;
  }

  /**
   * Sanitize component name
   */
  private static sanitizeComponentName(name: string): string {
    return name
      .replace(/[^a-zA-Z0-9]/g, '')
      .replace(/^\d+/, '')
      .replace(/^./, str => str.toUpperCase());
  }

  /**
   * Generate API route code
   */
  static generateApiRoute(appName: string): string {
    const routeName = appName.toLowerCase().replace(/\s+/g, '-');
    
    return `import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { prisma } from '@/lib/db';

export async function GET(req: NextRequest) {
  try {
    const session = await getServerSession();
    if (!session?.user?.email) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Fetch data from database
    const items = await prisma.${routeName}.findMany({
      orderBy: { createdAt: 'desc' },
    });

    return NextResponse.json(items);
  } catch (error) {
    console.error('Failed to fetch items:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession();
    if (!session?.user?.email) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    
    // Create new item
    const item = await prisma.${routeName}.create({
      data: {
        ...body,
        userId: session.user.id,
      },
    });

    return NextResponse.json(item);
  } catch (error) {
    console.error('Failed to create item:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}`;
  }

  /**
   * Generate type definitions
   */
  static generateTypeDefinitions(appName: string): string {
    const typeName = this.sanitizeComponentName(appName);
    
    return `export interface ${typeName}Item {
  id: string;
  title: string;
  description?: string;
  category?: string;
  status?: string;
  createdAt: Date;
  updatedAt: Date;
  userId: string;
}

export interface ${typeName}Filters {
  category?: string;
  status?: string;
  search?: string;
}

export interface ${typeName}State {
  items: ${typeName}Item[];
  selectedItem: ${typeName}Item | null;
  filters: ${typeName}Filters;
  isLoading: boolean;
}`;
  }
}

export default AppCodeGenerator;
